trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: azure-poc-vars
- name: IMAGE_TAG
  value: $(Build.BuildId)
- name: FULL_IMAGE_NAME
  value: $(ACR_LOGIN_SERVER)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'

    - script: |
        cd app
        npm ci
        npm run lint
      displayName: 'Static check / lint'

    - task: AzureCLI@2
      displayName: 'Build and push image to ACR'
      inputs:
        azureSubscription: 'azure-poc-azurerm'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(echo $(ACR_LOGIN_SERVER) | cut -d'.' -f1)

          docker build \
            -t $(FULL_IMAGE_NAME) \
            ./app

          docker push $(FULL_IMAGE_NAME)

- stage: DeployDev
  dependsOn: Build
  jobs:
  - job: DeployDev
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy image to DEV Container App'
      inputs:
        azureSubscription: 'azure-poc-azurerm'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az containerapp update \
            --name $(DEV_CONTAINER_APP_NAME) \
            --resource-group $(RESOURCE_GROUP_NAME) \
            --image $(FULL_IMAGE_NAME) \
            --set-env-vars \
              APP_ENVIRONMENT=dev \
              MESSAGE_PATH=/dev/message.json \
              STORAGE_ACCOUNT_NAME=$(STORAGE_ACCOUNT_NAME) \
              DATALAKE_CONTAINER_NAME=$(DATALAKE_CONTAINER_NAME) \
              BUILD_VERSION=$(Build.BuildId)

- stage: DeployQa
  dependsOn: DeployDev
  jobs:
  - job: DeployQa
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy same image to QA Container App'
      inputs:
        azureSubscription: 'azure-poc-azurerm'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az containerapp update \
            --name $(QA_CONTAINER_APP_NAME) \
            --resource-group $(RESOURCE_GROUP_NAME) \
            --image $(FULL_IMAGE_NAME) \
            --set-env-vars \
              APP_ENVIRONMENT=qa \
              MESSAGE_PATH=/qa/message.json \
              STORAGE_ACCOUNT_NAME=$(STORAGE_ACCOUNT_NAME) \
              DATALAKE_CONTAINER_NAME=$(DATALAKE_CONTAINER_NAME) \
	      BUILD_VERSION=$(Build.BuildId)
